# Generated by Django 3.1.6 on 2021-03-13 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20210302_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
