# Generated by Django 3.1.6 on 2021-04-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20210415_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
